### ISSUE TITLE
IndexError: index 2128 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by F-jie** [sakizuki/6DPoseAnnotator#1]
hi, thanks for your nice work, but when I use the data you provide and run command:
$python 6DoFPoseAnnotator.py
Error happened like this:
:: Load two point clouds to be matched.
Writing PLY: [========================================] 100%
Writing PLY: [========================================] 100%
Loading: data/hammer_mm.ply
Reading PLY: [========================================] 100%
Traceback (most recent call last):
  File "6DoFPoseAnnotator.py", line 197, in <module>
    img_mapped = mapping.Cloud2Image( CLOUD_ROT )
  File "6DoFPoseAnnotator.py", line 72, in Cloud2Image
    cloud_color = cloud_color1[cloud_np1[:,2].argsort()[::-1],:]
IndexError: index 2128 is out of bounds for axis 0 with size 0
What's the problem, thanks!

**Comment by sakizuki** [comment]
Thanks for using our code! The bug has been fixed.
