### ISSUE TITLE
Models too big or too small

### ISSUE THREAD

**Issue by Saafke** [sakizuki/6DPoseAnnotator#2]
Hi there,

When I am using the program, most of the time my models (the point clouds) are too big or too small to be aligned with the objects on the rgbd image. Even though my models (.ply) are accurate in size; and my camera matrix is correct too I believe. What could cause this and how do I fix this?

**Comment by sakizuki** [comment]
The program assumes the unit of 3D model is millimeter. If the unit of your model is meter, please try to uncomment the line 183 in 6DoFPoseAnnotator.py.
